name: Go

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Building
      run: go build -v ./cmd/... ./internal/...

    - name: Testing
      run: go test -cover ./cmd/... ./internal/...
